const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function normalizeImage(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('JPEG・PNG・WebPの10MB以下の画像を選んでください');
 const image=await createImageBitmap(file);try{if(image.width*image.height>50000000)throw Error('画像が大きすぎます。縮小して選び直してください');const scale=Math.min(1,1000/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',0.86));if(!blob||blob.type!=='image/webp'||blob.size>2*1024*1024)throw Error('画像変換に失敗しました。別の画像でお試しください');return blob;}finally{image.close();}
}
export function imageEditor(p,base){return `<section class="product-image"><strong>投稿用の商品画像</strong>${p.imagePath?`<img src="${esc(base+'/storage/v1/object/public/sumdex-products/'+p.imagePath)}" alt="登録した商品画像" loading="lazy"><button type="button" data-image-remove>画像の紐づけを外す</button>`:'<p>未登録：投稿は文章のみになります</p>'}<label class="file">画像ファイルを選ぶ<input data-image-file type="file" accept="image/jpeg,image/png,image/webp"></label><label>または画像URL<input data-image-source type="url" placeholder="https://cdn.snkrdunk.com/…"></label><button type="button" data-image-url>URLから画像を取り込む</button><small>参考画像です。使用可能な画像を登録してください。保存後「商品表を共有保存」を押してください。</small></section>`;}
function markdown(text){return esc(text).replace(/\[([^\]]+)\]\((https:\/\/discord\.com\/channels\/[\d/]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>');}
export function renderPostPreview(element,data){
 const d=data.destination;const destination=document.createElement('p');destination.textContent=`投稿先：${d.name} ／ チャンネルID ${d.channelId}`;element.replaceChildren(destination);
 const link=document.createElement('a');link.href=`https://discord.com/channels/${d.guildId}/${d.channelId}`;link.textContent='投稿先チャンネルを開く';link.target='_blank';link.rel='noopener noreferrer';element.append(link);
 for(const [i,message] of data.messages.entries()){const block=document.createElement('section');block.className='discord-preview';block.innerHTML=`<small>メッセージ ${i+1} / ${data.messages.length}</small><p>${markdown(message.content)}</p>${message.embeds.map(e=>`<article class="discord-embed"><h3>${esc(e.title)}</h3><p>${markdown(e.description)}</p>${e.image?`<img src="${esc(e.image.url)}" alt="${esc(e.title)}">`:''}</article>`).join('')}`;for(const img of block.querySelectorAll('img'))img.onerror=()=>{img.replaceWith(document.createTextNode('⚠ 画像を表示できません。商品画像を確認してください。'));};element.append(block);}
}
