import test from 'node:test';import assert from 'node:assert/strict';import {buildMessages} from '../src/posting.js';import {planCatalogImport} from '../src/catalog.js';
const p={id:'p',ja:'商品',en:'Golden Box',code:'',price:220000,imagePath:'a.webp'};
const row=g=>({productId:'p',conditions:[g],cost:200000,manualPrice:215000,expenses:0});
test('groups conditions in order with image, optional code, safe mentions',()=>{const [m]=buildMessages([row('b'),row('sa'),row('am')],[p],{},'https://example.com/');assert.equal(m.embeds.length,2);assert.equal(m.embeds[0].title,'Golden Box');const d=m.embeds[0].description;assert.ok(d.indexOf('S/A')<d.indexOf('AM'));assert.ok(d.indexOf('AM')<d.indexOf(' B'));assert.equal(m.embeds[0].thumbnail.url,'https://example.com/a.webp');assert.deepEqual(m.allowed_mentions,{parse:[]});});
test('loss requires explicit approval; price ceiling enforced',()=>{assert.throws(()=>buildMessages([{...row('b'),cost:250000}],[p],{},''),/赤字/);assert.equal(buildMessages([{...row('b'),cost:250000,allowLoss:true}],[p],{},'').length,1);assert.throws(()=>buildMessages([{...row('b'),manualPrice:230000}],[p],{},''),/超過/);});
test('splits within Discord embed/count limits and omits absent images',()=>{const ps=Array.from({length:24},(_,i)=>({...p,id:String(i),imagePath:''}));const messages=buildMessages(ps.map(p=>({...row('sa'),productId:p.id})),ps,{},'');assert.equal(messages.length,3);for(const m of messages){assert.ok(m.embeds.length<=10);assert.ok(m.embeds.reduce((n,e)=>n+e.title.length+e.description.length,0)<=6000);assert.equal(m.embeds[0].thumbnail,undefined);}});
test('old CSV imports preserve existing image association',()=>{const csv='id,ja,en,code,price,sourceUrl,checkedAt\np,商品,Golden Box,,220000,,';const result=planCatalogImport(csv,[p],()=> 'new');assert.equal(result.products[0].imagePath,'a.webp');});

test('category prefixes and edited text preserve image and disable mentions',async()=>{const {applyTextEdits}=await import('../src/posting.js');for(const [sourceUrl,prefix] of [['SUMdex-Price-List','Pokémon Card'],['One-Piece-Card-Price-List','ONE PIECE Card']]){const original=buildMessages([row('sa')],[{...p,sourceUrl}],{},'https://example.com/');assert.ok(original[0].embeds[0].title.startsWith(prefix));const edits=structuredClone(original);edits[0].content='**Edited**';edits[0].embeds[0].thumbnail.url='https://bad.test/';edits[0].allowed_mentions={parse:['everyone']};const result=applyTextEdits(original,edits);assert.equal(result[0].content,'**Edited**');assert.equal(result[0].embeds[0].thumbnail.url,'https://example.com/a.webp');assert.deepEqual(result[0].allowed_mentions,{parse:[]});edits[0].content='x'.repeat(2001);assert.throws(()=>applyTextEdits(original,edits));}});

test('compact prices, one list price per product and one shared guide across batches',()=>{const ps=Array.from({length:12},(_,i)=>({...p,id:String(i)}));const rows=ps.flatMap(p=>['b','sa','am'].map(g=>({...row(g),productId:p.id})));const messages=buildMessages(rows,ps,{},'https://example.com/');assert.equal(messages.flatMap(m=>m.embeds).filter(e=>e.title==='📋 Condition Guide').length,1);for(const e of messages.flatMap(m=>m.embeds).filter(e=>e.thumbnail)){assert.equal(e.image,undefined);assert.equal(e.description.split('SUMdex List:').length,2);assert.equal(e.description.split('\n').length,5);assert.match(e.description,/🟢 S\/A  \*\*¥215,000\*\* · −¥5,000/);}});
