import test from 'node:test';import assert from 'node:assert/strict';
import {calculate,recommendPriceBasis,generate,toggleCondition,conditionKey,normalizeConditionRow,DEFAULTS,parseCSV,domesticForProduct,nameKey} from '../src/pricing.js';
const p={id:'a',ja:'商品',en:'Mega Dream ex',code:'M2a',price:11800};
const row={id:'1',productId:'a',cost:11000,expenses:0,conditions:['sa'],discounts:{},basis:'sumdex',manualPrice:'',include:true,notes:''};
test('refund and clean price',()=>{const c=calculate(row,p,DEFAULTS,{});assert.equal(c.refund,1000);assert.equal(c.sale,11700);assert.equal(c.profit,1700);});
test('domestic floor cannot silently exceed SUMdex',()=>{const c=calculate({...row,basis:'domestic'},p,DEFAULTS,{shops:[{price:12200}]});assert.equal(c.sale,12200);assert.ok(c.errors.some(e=>e.includes('SUMdex価格を超過')));});
test('automatic price recommendation explains the safe choice',()=>{
 const ideal=recommendPriceBasis({...row,basis:'auto'},p,DEFAULTS,{shops:[{price:11500}]});assert.equal(ideal.basis,'sumdex');assert.equal(ideal.status,'ready');
 const floor=recommendPriceBasis({...row,basis:'auto'},p,DEFAULTS,{shops:[{price:11750}]});assert.equal(floor.basis,'domestic');assert.equal(calculate({...row,basis:'auto'},p,DEFAULTS,{shops:[{price:11750}]}).sale,11750);
 const higherDomestic=recommendPriceBasis({...row,basis:'auto'},p,DEFAULTS,{shops:[{price:12200}]});assert.equal(higherDomestic.basis,'sumdex');assert.equal(higherDomestic.status,'caution');
 const loss=recommendPriceBasis({...row,basis:'auto',cost:14000},p,DEFAULTS,{shops:[{price:11500}]});assert.equal(loss.status,'stop');
 const waiting=recommendPriceBasis({...row,basis:'auto'},{...p,price:''},DEFAULTS,{shops:[{price:11500}]});assert.equal(waiting.status,'waiting');
});
test('negative requires explicit permission and zero is allowed',()=>{assert.ok(calculate({...row,manualPrice:9999},p,DEFAULTS,{}).errors.some(e=>e.includes('赤字')));assert.equal(calculate({...row,manualPrice:9999,allowLoss:true},p,DEFAULTS,{}).errors.length,0);assert.equal(calculate({...row,manualPrice:10000},p,DEFAULTS,{}).errors.length,0);});
test('explicitly approved loss can be generated',()=>{const out=generate([{...row,cost:14000,allowLoss:true}],[p],DEFAULTS,{});assert.equal(out.errors.length,0);assert.match(out.text,/Mega Dream ex/);assert.equal(recommendPriceBasis({...row,cost:14000,allowLoss:true},p,DEFAULTS,{}).status,'caution');});
test('grade discount uses shared default and allows a product override',()=>{assert.equal(calculate({...row,conditions:['am']},p,DEFAULTS,{}).sale,11100);assert.equal(calculate({...row,conditions:['am'],discounts:{am:250}},p,DEFAULTS,{}).sale,11550);});
test('one condition grade is selected at a time',()=>{assert.deepEqual(toggleCondition(['sa'],'am',true),['am']);assert.deepEqual(toggleCondition(['am'],'b',true),['b']);});
test('old damage rows migrate to the three grade system without changing their discount',()=>{const migrated=normalizeConditionRow({...row,conditions:['shrinkSmall','dentSmall'],discounts:{dentSmall:200}},{clean:100,shrinkSmall:300,dentSmall:500});assert.equal(conditionKey(migrated),'am');assert.equal(migrated.discounts.am,600);assert.equal(calculate(migrated,p,DEFAULTS,{}).sale,11200);assert.equal(conditionKey({...row,conditions:['dentLarge']}),'b');});
test('same product and cost grouped, excluded and sensitive fields absent',()=>{const out=generate([row,{...row,id:'2',conditions:['am']},{...row,id:'3',include:false}], [p],DEFAULTS,{});assert.equal(out.errors.length,0);assert.equal(out.text.match(/Mega Dream ex/g).length,1);assert.ok(out.text.includes('🟡 **AM —'));assert.ok(!out.text.includes('11,000'));assert.ok(!out.text.includes('quantity'));});
test('condition lines are always ordered S/A, AM, B with color markers',()=>{const out=generate([{...row,id:'b',conditions:['b']},{...row,id:'am',conditions:['am']},{...row,id:'sa',conditions:['sa']}],[p],DEFAULTS,{});assert.equal(out.errors.length,0);assert.ok(out.text.indexOf('🟢 **S/A —')<out.text.indexOf('🟡 **AM —'));assert.ok(out.text.indexOf('🟡 **AM —')<out.text.indexOf('🔴 **B —'));});
test('CSV quoted commas and line breaks',()=>{assert.deepEqual(parseCSV('a,b\r\n"x,y","z\nq"'),[['a','b'],['x,y','z\nq']]);});
test('domestic Japanese aliases connect to English posting and SUMdex price',()=>{const product={...p,ja:'MEGAドリームex',domesticNames:'メガドリームex | ＭＥＧＡ ドリームex'};const domestic={'メガドリームex':{shops:[{site:'店A',price:11500}]},'MEGA ドリームex':{shops:[{site:'店B',price:11600}]}};assert.equal(calculate(row,product,DEFAULTS,domesticForProduct(domestic,product)).highest,11600);const post=generate([{...row,basis:'domestic'}],[product],DEFAULTS,domestic);assert.equal(post.errors.length,0);assert.match(post.text,/Mega Dream ex \[M2a\]/);assert.match(post.text,/¥11,700/);});
test('unknown Japanese label cannot silently satisfy domestic floor',()=>{const c=calculate({...row,basis:'domestic'},p,DEFAULTS,domesticForProduct({'他の商品':{shops:[{price:99999}]}},p));assert.ok(c.errors.some(e=>e.includes('国内買取価格を取得できていません')));});
test('set code spelling ignores case and width',()=>{assert.equal(nameKey(' SV11Ｂ '),nameKey('sv11b'));});

test('promotional template includes compact sales copy, ticket link, and condition guide',()=>{const out=generate([row],[p],DEFAULTS,{});assert.match(out.text,/DISCORD-EXCLUSIVE BOX DEALS/);assert.match(out.text,/SUMdex List Price: ¥11,800 \/ BOX/);assert.match(out.text,/📋 \*\*Condition Guide\*\*/);assert.match(out.text,/\*\*S:\*\* No holes, dents, or visible damage/);assert.match(out.text,/\*\*A:\*\* Only very minor, barely noticeable imperfections/);assert.match(out.text,/Open a ticket/);});

test('condition explanations appear once in a shared guide, not below every product',()=>{const out=generate([{...row,id:'sa',conditions:['sa']},{...row,id:'am',conditions:['am']},{...row,id:'b',conditions:['b']}],[p],DEFAULTS,{});assert.match(out.text,/🟢 \*\*S\/A\*\* — \*\*S:\*\* No holes/);assert.match(out.text,/🟡 \*\*AM\*\* — Visible dents or holes; best for opening/);assert.match(out.text,/🔴 \*\*B\*\* — Major dents or large holes; best for opening/);assert.equal(out.text.match(/No holes, dents, or visible damage/g).length,1);assert.match(out.text,/🟢 \*\*S\/A — ¥11,700 \/ BOX\*\* · 💸 ¥100 OFF/);});
